### PR TITLE
[QMS-119] Better handling of disabled and archived geocaches

### PR DESCRIPTION
**Pull request by pingurus**
**What is the linked issue for this pull request (start with a `#`):** QMS-#119

**Describe roughly what you have done:**

I added the possibility to filter for the status of a geocache and greyed out geocaches that are disabled.

**What steps have to be done to perform a simple smoke test:**

1. Open a file with active, disabled and archived geocaches
2. Filter for "status with archived" or similar
3. See that the icon is grey

**Does the code comply to the coding rules and naming conventions [Coding Guidleines](https://github.com/Maproom/qmapshack/wiki/DeveloperCodingGuideline):**

- [x] yes

**Is every user facing string in a tr() macro?**

- [x] yes

**Is the change user facing?**

- [x] yes,
- [ ] no

**If there are user facing changes did you add the ticket number and title into the changelog?**

- [x] yes, I didn't forget to change changelog.txt

### CODE REVIEW

**Comment by kiozen** [comment]
Instead of adding another bunch of icons that need to be maintained wouldn't it be better to gray scale these icons on-the-fly?

**Comment by pingurus** [comment]
> 
> 
> Instead of adding another bunch of icons that need to be maintained wouldn't it be better to gray scale these icons on-the-fly?

I tried to do so, but I couldn't make those keep the transparency. Thus I decided that it would save my time if I generate them with a tool that works on the first try.

**Comment by kiozen** [comment]
This mght not be the most beautiful code -  in fact it's a five minute hack - but in the core you have to save the alpha channel as mask and apply it to the gray scaled image, if that does not preserve the alpha channel by itself.
`    
    QPixmap pixmap("://icons/geocaching/icons/earth.png");
    QBitmap alpha = pixmap.createHeuristicMask();
    QImage image = pixmap.toImage().convertToFormat(QImage::Format_Grayscale8);
    QPixmap pixmap_gray = QPixmap::fromImage(image.convertToFormat(QImage::Format_ARGB32));
    pixmap_gray.setMask(alpha);
    pixmap_gray.save("test.png");
`

**Comment by pingurus** [comment]
Thanks!

**Pull request merged**
