### PR TITLE
Qms 3 Project does not compile because of missing sub-projects

### PR DESCRIPTION
**Pull request by kiozen**
Add the former sub-repos

* QMapTool
* qmt_map2jnx
* qmt_rgb2pct

into the code base.

### CODE REVIEW

**Comment by sikmir** [comment]
@kiozen As far as V_1.13.2 release tarball is essentially broken on GitHub (missed sub-repos) and the original V_1.13.2 tarball on BitBucket is removed, could you please make a correct release?

**Comment by kiozen** [comment]
> @kiozen As far as V_1.13.2 release tarball is essentially broken on GitHub (missed sub-repos) and the original V_1.13.2 tarball on BitBucket is removed, could you please make a correct release?

Don't think this is worth the effort of getting into the pressure to release something just because of an outdated source archive.

**Comment by sikmir** [comment]
> Don't think this is worth the effort of getting into the pressure to release something just because of an outdated source archive.

Well, but in such case Linux distributions' qmapshack package maintainers have no way to update it to 1.13.2, since official source archive is broken and there is no way to build it.

**Comment by kiozen** [comment]
I guess the package maintainers already did their homework when the version was released on bitbucket. And they are clever enough to pull the taged version from the hg repository.

**Comment by sikmir** [comment]
> I guess the package maintainers already did their homework when the version was released on bitbucket.

Indeed, they did (when the version was released on BB, e.g. [ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/sci-geosciences/qmapshack/qmapshack-1.13.2.ebuild)). And one day... the link `https://bitbucket.org/maproom/qmapshack/downloads/qmapshack-1.13.2.tar.gz` turned into a pumpkin.

> And they are clever enough to pull the taged version from the hg repository.

And one day (June 1, 2020)... hg repository will turn into a pumpkin.

**Pull request merged**
