### PR TITLE
[QMS-526] Fix deprecation warnings

### PR DESCRIPTION
**Pull request by kiozen**
### What is the linked issue for this pull request:
[comment]: # (Add the ticket number behind QMS-# )

QMS-#526

### What you have done:
[comment]: # (Describe roughly.)

Removed all deprecation warnings.

### Steps to perform a simple smoke test:
[comment]: # (List the steps.)

@mitxel-m @wthaem @pingurus we need to test this a good as possible. Can you please compile and test this version by using it?

### Does the code comply to the coding rules and naming conventions [Coding Guidelines](https://github.com/Maproom/qmapshack/wiki/DeveloperCodingGuideline):

- [x] yes

### Is every user facing string in a tr() macro?

- [x] yes

### Did you add the ticket number and title into the changelog? Keep the numeric order in each release block.

- [x] yes, I didn't forget to change changelog.txt

### CODE REVIEW

**Comment by wthaem** [comment]
Compiling and first quick check (QMS): no problems.

Qt 5.15.2
GDAL 3.4.2
Proj 9.0.0
Routino 3.3.3
latest BRouter

Windows 10
VisualStudio 2019
cmake 3.23.0

**Comment by wthaem** [comment]
Results of playing with compiler flags:

* With /WD9999 (unknown code, didn't know how to do better):

    In `CGisListWks.cpp, CDBItem.cpp, IDBFolder.cpp, CQlgtDb.cpp`:

        warning C4003: Nicht genügend Argumente für den Aufruf des funktionsähnlichen Makros "QUERY_EXEC". 

    In `alglib`:

        warning C4005: "_CRT_SECURE_NO_WARNINGS": Makro-Neudefinition

        warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an.

* With "Wall" long list of warnings

* With "W4": plenty of warnings

* With "W3": in addition to /WD9999 warnings: a lot of C4996 warnings

    Many of them:

        warning C4996: 'QComboBox::AdjustToMinimumContentsLength': Use AdjustToContents or AdjustToContentsOnFirstShow

        warning C4996: 'QPainter::HighQualityAntialiasing': Use Antialiasing instead

        warning C4996: 'Qt::SystemLocaleLongDate': Use QLocale

        warning C4996: 'Qt::SystemLocaleShortDate': Use QLocale

        warning C4996: 'QPalette::Foreground': UseQPalette::WindowText instead

        warning C4996: 'QPalette::Background': Use QPalette::Window instead

        warning C4996: 'QComboBox::AdjustToMinimumContentsLength': Use AdjustToContents or AdjustToContentsOnFirstShow

    once:

        warning C4101: "e": Unreferenzierte lokale Variable (CMainWindow.cpp(1922,29):

**Comment by kiozen** [comment]
I fixed the Qt related warnings. Everything else is out of scope of this ticket.

**Comment by wthaem** [comment]
There are still a few C4996 left:

    CDetailsGeoCache.cpp(67,64), 
    CDetailsGeoCache.cpp(135,59): warning C4996: 'Qt::SystemLocaleShortDate': Use QLocale

    CRouterBRouterTilesSelect.cpp(820,72), 
    CRouterBRouterTilesSelect.cpp(822,73), 
    CRouterBRouterTilesSelect.cpp(828,72), 
    CRouterBRouterTilesSelect.cpp(834,73): warning C4996: 'Qt::DefaultLocaleShortDate': Use QLocale

    CGisItemWpt.cpp(1250,51): warning C4996: 'Qt::SystemLocaleShortDate': Use QLocale

**Comment by kkarsten62** [comment]
I already saw the warnings when compiling the different AppImages. But at at the end the executables will be built :+1: 
I can check for Qt version 5.9.5, 5.12.7, 5.12.2, 5.15.7 within the different AppImages docker files.

@kiozen : Please give me an helping hand. What to do the pull this QMS-526 from the repo? But I will last some days due to some load in my business.

**Comment by kiozen** [comment]
Get the branch form this repo:
https://github.com/kiozen/qmapshack/tree/QMS-526

No need to test all those versions. The cmake script sets the minimum version to Qt 5.15.2 and that's it. It's more important to find bugs caused by the fixes.

**Comment by kkarsten62** [comment]
Just for clarification.

Does it mean by setting the minimum version to Qt 5.15.2 that Ubuntu 18.04 (Qt 5.9.5), Ubuntu 20.04 (Qt 5.12.8) and OpenSUSE 15.2 (Qt 5.12.7) will no longer supported by the official Qt distribution packages?

So this Linux distribution should do then a dedicated Qt 5.15.2 installation?

**Comment by kkarsten62** [comment]
I have just compiled AppImages with Ubuntu 22.04 (Qt 5.15.3) and Fedora 33 (Qt 5.15.2). Deprecation warnings seems to be eliminated. Some compiler warnings still shown, see log files. I did some simple tests (create a track, edit some values, etc.). Seems to be working as expected.

[Fedora-33_Qt-15.2.log](https://github.com/Maproom/qmapshack/files/8840457/Fedora-33_Qt-15.2.log)
[Ubuntu-22.04_Qt-15.3.log](https://github.com/Maproom/qmapshack/files/8840458/Ubuntu-22.04_Qt-15.3.log)

**Comment by kiozen** [comment]
This might break some of the older distributions. But what is the point to delay progress just because users do not want to update distribution?

I will have a look into the warnings the next days. Thanks for testing

**Comment by kkarsten62** [comment]
I personally will not have an issues with that. openSUSE 15.2 is out of support since January and Ubuntu 18.04 will be out of support in March 2023. But Ubuntu 20.04 is quite popular and will be in support till March 2025. I will check how to setup a dedicated Docker file to build an AppImage for Ubuntu 20.04. Let's go ahead to support Qt 5.15.2. :+1:

**Comment by kiozen** [comment]
Fixed all deprecation warnings reported. 

The others are of scope. 
* alglib has to fix their warnings on their. Maybe updating the code might help. But this is another ticket.
* I couldn't resolve the warnings with QVector. No clue what's the problem.

**Comment by kiozen** [comment]
@kkarsten62 You can try to lower the version for the older distributions. The Qt API was migrating over the versions. I can't tell what's the lowest version that does not break. Anyways, Qt 5.15 is the last for Qt5 and I expect all migration done on that version,

**Pull request merged**
