### PR TITLE
[QMS-354]   Refactor the code to get rid of clazy warnings

### PR DESCRIPTION
**Pull request by kiozen**
**What is the linked issue for this pull request (start with a `#`):**

QMS-#354

**Describe roughly what you have done:**

Ran the clang/clazy code analysis for all cpp files in the project fixing most of the 
messages. Some are  false positives.

**What steps have to be done to perform a simple smoke test:**

This is changing the code at many locations. The only way to test is using QMapShack 
and reporting bugs. 

**Does the code comply to the coding rules and naming conventions [Coding Guidelines](https://github.com/Maproom/qmapshack/wiki/DeveloperCodingGuideline):**

- [x] yes

**Is every user facing string in a tr() macro?**

- [x] yes

**Did you add the ticket number and title into the changelog? Keep the numeric order in each release block.**

- [x] yes, I didn't forget to change changelog.txt

### CODE REVIEW

**Comment by kiozen** [comment]
@wthaem, @pingurus @mitxel-m you might want to compile and test this version. I hope I didn't introduce bugs but you never know. 

I still have to do the fixes for QMapTool.

**Comment by wthaem** [comment]
* Compilation: no problems.
* Issue QMS-357: tried to crash QMS - failed (but this version comes without POI support, QMS-357 crashs happened with POI support!)

**Comment by kiozen** [comment]
>     * Issue QMS-357: tried to crash QMS - failed (but this version comes without POI support, QMS-357 crashs happened with POI support!)

Just to make sure: Is that good or bad?

**Comment by wthaem** [comment]
> Just to make sure: Is that good or bad?

For current commit: it is good. Let's see what happens with POI code.

**Comment by pingurus** [comment]
Compiles for me, found no obvious bugs.
The crash on closing that i reported earlier persists, might it have to do with the warning I get, that gdal uses libproj.so.19 whilst some part of the code uses .21?

**Comment by kiozen** [comment]
Yes linkage to different versions of a library within a single app is bad.

I merge it. It's impossible to review.

**Comment by kiozen** [comment]
@pingurus I rebased the `feature/pois` branch. In the future please use clang-tidy and clazy to cleanup your code. If you haven't disabled them in QtCreator the IDE should analyze the code while you write.

**Pull request merged**
