### PR TITLE
[QMS 480] QMapShack for macOS

### PR DESCRIPTION
**Pull request by d029940**
### What is the linked issue for this pull request:
[comment]: # (Add the ticket number behind QMS-# )

QMS-#480

### What you have done:
[comment]: # (Describe roughly.)

Overhaul of build-scripts to automate building QMS for Mac.
Adapted CMakeLists.txt to include Apple specifics:
- Reflect the build philosophy to first use external packages from homebrew. If they are not available , create the packages (quazip and routino) in a local folder (preferably under the top-level QMS build folder).
- Binaries released: https://github.com/d029940/qmapshack/releases/tag/v16.1.1-macOS.13-ARM

### Steps to perform a simple smoke test:
[comment]: # (List the steps.)

Follow the instructions of README.md in the MacOS folder to build QMS for Mac 

### Does the code comply to the coding rules and naming conventions [Coding Guidelines](https://github.com/Maproom/qmapshack/wiki/DeveloperCodingGuideline):

- [X] yes

### Is every user facing string in a tr() macro?

- [X] yes

### Did you add the ticket number and title into the changelog? Keep the numeric order in each release block.

- [X] yes, I didn't forget to change changelog.txt

### CODE REVIEW

**Comment by kiozen** [comment]
The commit history has to be squashed and rebased to latest dev branch. Do you know how to do that? Do you need help? Or should I simply do it?

**Comment by d029940** [comment]
> The commit history has to be squashed and rebased to latest dev branch. Do you know how to do that? Do you need help? Or should I simply do it?

I am sorry, I don't. Next thing to learn. Please do it. 

I was not sure if I needed to copy my dev version of QMS to a branch QMS-480. But I remember somehow, that this is requested.

I think, once you pointed me to a description. I cannot find it anymore. If you don't mind, please provide it again.

**Comment by d029940** [comment]
Currently all known problems for MacOS bundling for QMapShack.app are fixed. There is also a release on GitHub.
I tried to rebase but I had some problems. So, I stopped it. Can you do it for me? And maybe point me to some piece of info on howto do it in the future.
The current branch is QT-480.
As soon this is merged into the origin repo, I will delete QT-480 branch. And make a complete new fork (or rebase my dev branch on yours(.

Then I will start looking if I can have an option to also run QMS on brew installed packages for preparation of a brew package of QMS.

**Comment by kiozen** [comment]
Ok, I rebased the code to the dev branch of the main repository.  That was a tough one :smile: You did some really nasty stuff in your fork like committing on dev and merging dev into the QMS-480 branch. That is called a Foxtrot merge and is considered as evil :smiling_imp: 

Anyways I hope I didn't break anything. Please review and test again.

For the future try to stick to the process as described in https://github.com/Maproom/qmapshack/wiki/DeveloperCommitCode#commit-code

Basically this is:
* fetching dev from upstream and merging it into your local dev.
* rebase your development branch QMS-XXX on your local dev (that should be equal to the upstream one)

see https://github.com/Maproom/qmapshack/wiki/DeveloperCommitCode#rebase-your-branch

Never merge any dev or master branch into your develop branch. Always rebase.

You can cleanup your branch with an interactive rebase:

https://github.com/Maproom/qmapshack/wiki/DeveloperCommitCode#change-commits

**Comment by d029940** [comment]
I will check it. But give some advice.

- I forked QMS dev in my own dev. Did almost everything in this branch. Then I copied my dev to a QMS-480 branch, because I thought it should have the same name as this issue, which is named QMS-480. Obviously  something wrong.

**Comment by d029940** [comment]
I am sorry for the confusion. I a not sure when and where I diverged from the procedure.
Thank you for your hard work.

Now with respect to testing:
- Everything works when compiling GDAL myself.
- When using homebrew's GDAL there is a mistake in the build-QMS.sh script.

I corrected it on my local machine and wait for your advice if I should commit it and go on with 
[https://github.com/Maproom/qmapshack/wiki/DeveloperCommitCode#change-commits](https://github.com/Maproom/qmapshack/wiki/DeveloperCommitCode#change-commits)

When everything is in your repo, can I just delete my QMS-480 branch?

I am still trying to understand the whole process of committing to QMS. I created a powerpoint
[Commiting to QMS.pptx](https://github.com/Maproom/qmapshack/files/10196259/Commiting.to.QMS.pptx)

**Comment by d029940** [comment]
I moved the file with the small change to a location outside of the local directory, and cloned the branch QMS-480 to my local machine. So, remote and local are absolutely identical. (I will apply the small change later, because QMS will still build with GDAL).

If I follow the procedure in [https://github.com/Maproom/qmapshack/wiki/DeveloperCommitCode#change-commits](https://github.com/Maproom/qmapshack/wiki/DeveloperCommitCode#change-commits), I assume that everything is done up to "Rebase your branch".

So, I did the steps: 
$ git checkout dev. --> ok
$ git fetch upstream --> ok
$ git merge upstream/dev --> ok
$ git checkout QMS-480 --> ok
$ git rebase dev --> conflict

Auto-merging MacOSX/build-gdal.sh
Auto-merging MacOSX/build_files_v1/env_build_vars.sh
Auto-merging MacOSX/bundle-env-path.sh
CONFLICT (content): Merge conflict in MacOSX/bundle-env-path.sh
Auto-merging MacOSX/bundle-qmapshack.sh
CONFLICT (content): Merge conflict in MacOSX/bundle-qmapshack.sh
error: could not apply 21e9cbb3... copy complete gdal lib into bundle
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 21e9cbb3... copy complete gdal lib into bundle

Since, I do not know what to do, I did a `git rebase --abort` to avoid another mess.

Are we stuck?

**Comment by kiozen** [comment]
I assume that after fetching and merging your local dev branch matches the one if the main repository. You can check with `git log` and compare hashes. 

Now you checkout your branch QMS-480. If it is the one with my last commit it should only contain a single commit. You can check again with `git log`. If that is the case the rebase should do nothing. 

As your rebase has conflicts, I doubt you are on the right branches. You might do a `git pull` on the QMS-480 branch. After my change this should end up in conflicts if you still have your local branch. The is because of the rebase that changes all hashes. When I pushed the rebased branch I had to do a forced push `git push --force-with-lease`.  In that case you usually do a `git reset --hard origin/QMS-480` as you want to remove all old stuff and simply take over what's in the remote repo. 

Another reason for conflicts can be that you added new commits and rebasing the branch now has some conflicts with dev. In that case you have to resolve the conflicts. I usually use Visual Code for that. Git has added a few lines in your conflicting file framing the current and incoming changes. You have to decide what change is correct and select it. You can do that in Visual Code or you simply remove the lines including the framing ones. When done you have to do `git add <file>`on the conflicting files and then `git rebase --continue`

**Comment by kiozen** [comment]
In step 13 the shit hit the fan :wink: 

Usually you would do a `git merge upstream/dev`. However you did some local commits on dev. You shouldn't do that. The commits break your rebase, now.

To weasel out of this. 
```
git checkout dev
git fetch upstream
git reset --hard upstream/dev
git push --forece-with-lease
```
Now you local, origin dev and upstream dev should be all the same. Check with `git log`.

If you switch to your QMS-480 branch a rebase to dev should be no problem.

**Comment by d029940** [comment]
I cloned again my fork of qmapshack to an empty folder and did the steps you mentioned:

```
git checkout dev
git fetch upstream
git reset --hard upstream/dev
git push --force-with-lease
```

Now my dev branch on GitHub is the same as yours. I think this is a good sign.

Switching on my machine to branch QMS-480 and do a 

`git rebase dev`
results in: Current branch QMS-480 is up to date.

If I would summarise:
- my fork of qmapshack, dev branch is identical to your dev branch
- my branch QMS-480 has all the updated files and is one commit ahead of yours, because of the rebase work you did.

Is that now correct?

I assume that somewhere in the future you will apply the PR QMS-480. After that I can:
1. delete my branch of QMS-480
2. update my dev branch from yours.

And in the future I will create an issue with a PR QMS-XXX, branch my dev to a QMS-XXX branch, and ONLY work on the QMS-XXX branch.

**Comment by kiozen** [comment]
As far as I can see all correct.

**Comment by kiozen** [comment]
Ok, then let's get it rolling!  

A huge thanks and a lot of respect that you digged your way into that. Starting from zero to that level is very impressive. I am sure your work is really appreciated not just by me but by many other Mac users. 

I try to do another official release over the holidays.

**Pull request merged**
