### PR TITLE
[QMS-73] Info of a geocache is not correctly shown in Copy Element Window

### PR DESCRIPTION
**Pull request by kiozen**
**What is the linked issue for this pull request (start with a `#`):** QMS-#73

**Describe roughly what you have done:**

* Finetune dialog layout
* Create getLastLog() and getLogs() in CGisItemWpt::geocache_t
* Enhance getInfo() text for geocache

**What steps have to be done to perform a simple smoke test:**

* Open a pocket query
* Copy first cache into another project
* Copy the same cache into the same project

Enhanced test:

* Get an updated pocket query
* Copy the same cache into the same project

**Does the code comply to the coding rules and naming conventions [Coding Guidleines](https://github.com/Maproom/qmapshack/wiki/DeveloperCodingGuideline):**

- [x] yes

**Is every user facing string in a tr() macro?**

- [x] yes

**Is the change user facing?**

- [x] yes,
- [ ] no

**If there are user facing changes did you add the ticket number and title into the changelog?**

- [x] yes, I didn't forget to change changelog.txt

### CODE REVIEW

**Comment by pingurus** [comment]
When resizing, the infomation is still sometimes lost, even though there would be enough place:
grafik
Even more extreme:
grafik

**Comment by kiozen** [comment]
This looks like the old code with broken layout. Are you sure you used branch QMS-73?

**Comment by pingurus** [comment]
The layout is correct now, I don't know why, since I compiled it off the same branch :laughing: 
However, the timezone is not respected (I do not mind about the format):
grafik
When I open the same project's edit window, it shows this:
grafik

**Comment by kiozen** [comment]
> The layout is correct now, I don't know why, since I compiled it off the same branch laughing
> However, the timezone is not respected (I do not mind about the format):

Good point. I will fix.

**Comment by kiozen** [comment]
@pingurus Please test again

**Comment by pingurus** [comment]
All fine now, thanks!

**Pull request merged**
